apiVersion: apps/v1
kind: Deployment
metadata:
  name: edc-operator-services
  namespace: edc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edc-operator-services
  template:
    metadata:
      labels:
        app: edc-operator-services
    spec:
      containers:
        - name: edc-operator-services
          image: edc-operator-services:local
          ports:
            - containerPort: 8186
          env:
            - name: EDC_DB_HOST
              value: "edc-mysql"
            - name: EDC_DB_PORT
              value: "3306"
            - name: EDC_DB_NAME
              value: "edc"
            - name: EDC_DB_USER
              value: "edc"
            - name: EDC_DB_PASSWORD
              value: "edc"
            - name: EDC_KAFKA_BOOTSTRAP
              value: "edc-kafka:9092"
            - name: EDC_KAFKA_GROUP
              value: "edc-operator-services"
---
apiVersion: v1
kind: Service
metadata:
  name: edc-operator-services
  namespace: edc
spec:
  selector:
    app: edc-operator-services
  ports:
    - port: 8186
      targetPort: 8186
